### ISSUE TITLE
Issue with reading in suffixes

### ISSUE THREAD

**Issue by lorrainea** [nicolaprezza/rk-lce#1]
Hi, I am trying to run this with a file containing a list of suffix positions (with the first line of the file containing the number of suffixes) but get the following error:

terminate called after throwing an instance of 'std::length_error'
what():  cannot create std::vector larger than max_size()
Aborted (core dumped)

Do you have any working input files to test the code with?
Thank you

**Comment by nicolaprezza** [comment]
Hi Lorraine!

It's been a while since I've worked on this code (7 years:) ... what exactly are you running? 

After compiling test.cpp, the structure can be tested simply as 

./test path rep

where path is the path of the text file on which the lce structure is built, and rep is an integer specifying the number of LCE queries to run during the benchmark. 

If, after running the above command, you still get the same error, please send me the input file that generates the problem so I can replicate the bug. 

best
Nicola

**Comment by lorrainea** [comment]
Hi
./test is working as it should but I am trying to output a sorted subset of text positions using ./sa-rk. 
Attached is a smaller example that gives a what():  std::bad_alloc error. 
Is the format of the positions.txt file incorrect?

./sa-rk text.txt out positions.txt

[text.txt](https://github.com/nicolaprezza/rk-lce/files/11272071/text.txt)
[positions.txt](https://github.com/nicolaprezza/rk-lce/files/11272075/positions.txt)

Thanks

**Comment by nicolaprezza** [comment]
Ah, sure: you're providing the text positions in ASCII rather than as 64-bits unsigned integers (see the short manual that appears after running ./sa-rk). 

In other words: positions.txt should not be a text file, but a binary file. If you want to sort s positions, the file should contain exactly (s+1)*8 bytes. The first 8 bytes (64 bits) encode s (as a uint64_t). The remaining s*8 bytes encode the s positions, each encoded in 8 bytes (64 bits) as uint64_t integers. You can create such a file with a short C++ program.
